// Code generated by "stringer -type=NonTerminal"; DO NOT EDIT.

package parser

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Sig-0]
	_ = x[Params-1]
	_ = x[Param-2]
	_ = x[Params1-3]
	_ = x[Ret-4]
}

const _NonTerminal_name = "SigParamsParamParams1Ret"

var _NonTerminal_index = [...]uint8{0, 3, 9, 14, 21, 24}

func (i NonTerminal) String() string {
	if i < 0 || i >= NonTerminal(len(_NonTerminal_index)-1) {
		return "NonTerminal(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NonTerminal_name[_NonTerminal_index[i]:_NonTerminal_index[i+1]]
}
