// Code generated by "stringer -type=Terminal"; DO NOT EDIT.

package parser

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LP-0]
	_ = x[RP-1]
	_ = x[EOF-2]
	_ = x[FUN-3]
	_ = x[ID-4]
	_ = x[COL-5]
	_ = x[COM-6]
}

const _Terminal_name = "LPRPEOFFUNIDCOLCOM"

var _Terminal_index = [...]uint8{0, 2, 4, 7, 10, 12, 15, 18}

func (i Terminal) String() string {
	if i < 0 || i >= Terminal(len(_Terminal_index)-1) {
		return "Terminal(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Terminal_name[_Terminal_index[i]:_Terminal_index[i+1]]
}
