// Code generated by "stringer -type=NonTerminal"; DO NOT EDIT.

package parser

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[S-0]
	_ = x[E-1]
	_ = x[E1-2]
	_ = x[T-3]
	_ = x[T1-4]
	_ = x[F-5]
	_ = x[L1-6]
	_ = x[L-7]
}

const _NonTerminal_name = "SEE1TT1FL1L"

var _NonTerminal_index = [...]uint8{0, 1, 2, 4, 5, 7, 8, 10, 11}

func (i NonTerminal) String() string {
	if i < 0 || i >= NonTerminal(len(_NonTerminal_index)-1) {
		return "NonTerminal(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NonTerminal_name[_NonTerminal_index[i]:_NonTerminal_index[i+1]]
}
