// Code generated by daniil-ushkov LL(1) parser generator; DO NOT EDIT.
package parser

//go:generate stringer -type=Terminal
type Terminal int

const (
	RP Terminal = iota
	NUM
	PLUS
	SUB
	MUL
	LP
	EOF
	LOG
	DIV
)

//go:generate stringer -type=NonTerminal
type NonTerminal int

const (
	S NonTerminal = iota
	E
	E1
	T
	T1
	F
	L1
	L
)
