// Code generated by "stringer -type=Terminal"; DO NOT EDIT.

package parser

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RP-0]
	_ = x[NUM-1]
	_ = x[PLUS-2]
	_ = x[SUB-3]
	_ = x[MUL-4]
	_ = x[LP-5]
	_ = x[EOF-6]
	_ = x[LOG-7]
	_ = x[DIV-8]
}

const _Terminal_name = "RPNUMPLUSSUBMULLPEOFLOGDIV"

var _Terminal_index = [...]uint8{0, 2, 5, 9, 12, 15, 17, 20, 23, 26}

func (i Terminal) String() string {
	if i < 0 || i >= Terminal(len(_Terminal_index)-1) {
		return "Terminal(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Terminal_name[_Terminal_index[i]:_Terminal_index[i+1]]
}
