// Code generated by "stringer -type=NonTerminal"; DO NOT EDIT.

package parser

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[E1-0]
	_ = x[T-1]
	_ = x[T1-2]
	_ = x[F-3]
	_ = x[S-4]
	_ = x[E-5]
}

const _NonTerminal_name = "E1TT1FSE"

var _NonTerminal_index = [...]uint8{0, 2, 3, 5, 6, 7, 8}

func (i NonTerminal) String() string {
	if i < 0 || i >= NonTerminal(len(_NonTerminal_index)-1) {
		return "NonTerminal(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NonTerminal_name[_NonTerminal_index[i]:_NonTerminal_index[i+1]]
}
