// Code generated by daniil-ushkov LL(1) parser generator; DO NOT EDIT.
package parser

//go:generate stringer -type=Terminal
type Terminal int

const (
	MUL Terminal = iota
	DIV
	LP
	RP
	EOF
	NUM
	PLUS
	SUB
)

//go:generate stringer -type=NonTerminal
type NonTerminal int

const (
	E1 NonTerminal = iota
	T
	T1
	F
	S
	E
)
