// Code generated by "stringer -type=Terminal"; DO NOT EDIT.

package parser

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MUL-0]
	_ = x[DIV-1]
	_ = x[LP-2]
	_ = x[RP-3]
	_ = x[EOF-4]
	_ = x[NUM-5]
	_ = x[PLUS-6]
	_ = x[SUB-7]
}

const _Terminal_name = "MULDIVLPRPEOFNUMPLUSSUB"

var _Terminal_index = [...]uint8{0, 3, 6, 8, 10, 13, 16, 20, 23}

func (i Terminal) String() string {
	if i < 0 || i >= Terminal(len(_Terminal_index)-1) {
		return "Terminal(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Terminal_name[_Terminal_index[i]:_Terminal_index[i+1]]
}
